config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#dashboard"

  resources :beans, only: [ :index, :show ]

  resources :categories, only: [:index]

  resources :cart_items

  resources :cart

  resources :users, only: [:new, :create]

  resources :sessions, only: [:destroy]

  namespace :admin do
    get 'dashboard', to: 'dashboard#dashboard'
    resources :orders, only: [:update, :show]
    resources :beans, only: [:new, :create, :index, :edit, :show, :update]
  end

  resources :orders, only: [:create, :show, :index]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/dashboard', to: 'users#show'

  get '/:category_name', to: 'categories#show', as: 'category'


end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_beans
  has_many :beans, through: :order_beans

  def self.ordered_count
    where(status:"Ordered").count
  end

  def self.paid_count
    where(status:"Paid").count
  end

  def self.cancelled_count
    where(status:"Cancelled").count
  end

  def self.completed_count
    where(status:"Completed").count
  end

  def item_count
    order_beans.sum(:quantity)
  end

  def date
    created_at.strftime('%m/%d/%Y %I:%M %p')
  end

  def completed_or_cancelled?
    status == 'Completed' || 'Cancelled'
  end

  def update_time
    updated_at.strftime('%m/%d/%Y %I:%M %p')
  end

  def self.build_order(cart, user)
    order = user.orders.create(total_price: cart.total_price)
    cart.items.each do |cart_item|
      order.order_beans.create(bean_id: cart_item.id,
                              quantity: cart_item.quantity,
                              price: cart_item.price,
                              subtotal: (cart_item.quantity * cart_item.price),
                              item_title: cart_item.title,
                              )
    end
    order
  end
end

app/models/order_bean.rb
class OrderBean < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController

  def update
    if Order.find(params[:id]).update(status: params[:status])
    redirect_back(fallback_location: 'admin/dashboard')
    end
  end

  def show
    @order = Order.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def create
    @order = Order.build_order(@cart, current_user)
    flash[:success] = 'Order was successfully placed'
    session[:cart].clear
    render :show
  end

  def show
    if current_user == nil || !current_user.orders.include?(Order.find(params[:id]))
      render file: '/public/404'
    else
      @order = current_user.orders.find(params[:id])
      
      render :show
    end
  end

  def index
    @orders = current_user.orders
  end
end

app/views/orders/index.html.erb
<h1>Order History</h1>


<table class="table table-striped" id="orders-table">
  <tr>
    <th>Order Number</th>
    <th>Item Count</th>
    <th>Order Date</th>
    <th>Total Price</th>
    <th>View</th>
  </tr>
    <% @orders.each do |order| %>
      <tr>
        <td id='order-id'><%= order.id %></td>
        <td id='order-item-count'><%= order.item_count %></td>
        <td id='order-date'><%= order.date %></td>
        <td id='order-total'>$<%= order.total_price %></td>
        <td id='view-order-button'><%= button_to 'View Order', order_path(order), method: :get %></td>
      </tr>
    <% end %>
</table>

app/views/orders/show.html.erb
<h1>Your Most Recent Order</h1>

<table class="table table-striped" id="order-table">
  <tr>
    <th>Item</th>
    <th>Quantity</th>
    <th>Price</th>
  </tr>
    <% @order.order_beans.each do |order_bean| %>
      <tr>
        <td id='item-link'><%= link_to "#{order_bean.item_title}", bean_path(order_bean.bean_id) %></td>
        <td id='item-quantity'><%= order_bean.quantity %></td>
        <td id='item-subtotal'>$<%= order_bean.subtotal %></td>
      </tr>
    <% end %>
</table>
<div id="order_info">
  <p id='order-total'>Total: $<%= @order.total_price %></p>
  <p id='order-status'>Status: <%= @order.status %></p>
  <p id='order-created-date'>Order Sent: <%= @order.date %></p>
  <% if @order.completed_or_cancelled? %>
    <p id='order-updated-date'>Order Updated to <%= @order.status %> at <%= @order.update_time %></p>
  <% end %>
</div>