config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#dashboard"

  resources :beans, only: [ :index, :show ]

  resources :categories, only: [:index]

  resources :cart_items

  resources :cart

  resources :users, only: [:new, :create]

  resources :sessions, only: [:destroy]

  namespace :admin do
    get 'dashboard', to: 'dashboard#dashboard'
    resources :orders, only: [:update, :show]
    resources :beans, only: [:new, :create, :index, :edit, :show, :update]
  end

  resources :orders, only: [:create, :show, :index]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/dashboard', to: 'users#show'

  get '/:category_name', to: 'categories#show', as: 'category'


end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  validates :name, presence: true, uniqueness: true
  before_create :slug
  friendly_id :name, use: :slugged
  has_many :bean_categories
  has_many :beans, through: :bean_categories

  private

   def slug
    self.slug = name.downcase.gsub(/[^a-z1-9]+/, '-').chomp('-')
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end
  def show
    @category = Category.friendly.find(params[:category_name])
  end
end

app/views/categories/index.html.erb
<h2>Coffee Categories</h2>

<div class="row">
<% @categories.each do |category| %>
  <div class="col-sm-4 col-md-3">
    <div class="thumbnail">
       <%= image_tag "coffee 2.jpg"%>
      <div class="caption">
        <h3><%= category.name %></h3>
        <p><%= button_to "Shop Now", category_path(category),  class: "btn btn_danger", method: 'get' %></p>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/categories/show.html.erb
<h1 class="all-beans"><%= @category.name %></h1>
<div class="row">
<% @category.beans.each do |bean| %>
  <div class="col-sm-4 col-md-3">
    <div class="thumbnail">
      <div class="bean_pic">
      <%= image_tag bean.image.remote_url %>
    </div>
      <div class="caption">
        <h3 class="bean_stats"><%= link_to bean.title, bean_path(bean) %></h3>
        <p class = "bean_stats">Description: <%= bean.description %></p>
        <p class = "bean_stats">Price: <%= bean.price %></p>
        <div class = "bean_button">
        <p class = "bean_stats"> <%= button_to "Add Item", cart_items_path(bean_id: bean.id),  class: "btn btn_danger"%></p>
      </div>
      </div>
    </div>
  </div>
  <% end %>
</div>