config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#dashboard"

  resources :beans, only: [ :index, :show ]

  resources :categories, only: [:index]

  resources :cart_items

  resources :cart

  resources :users, only: [:new, :create]

  resources :sessions, only: [:destroy]

  namespace :admin do
    get 'dashboard', to: 'dashboard#dashboard'
    resources :orders, only: [:update, :show]
    resources :beans, only: [:new, :create, :index, :edit, :show, :update]
  end

  resources :orders, only: [:create, :show, :index]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/dashboard', to: 'users#show'

  get '/:category_name', to: 'categories#show', as: 'category'


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :cart

  helper_method :current_user


  def dashboard
   render :dashboard
  end

  def cart
    @cart ||= Cart.new(session[:cart])
  end

  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def user!
    render file: '/public/404' unless current_user
  end

  def current_admin?
  current_user && current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/admin_dashboard.html.erb
<h1 class="admin-header">Admin Dashboard</h1><br>
<h4 id="view-orders-by">View Orders By:</h4>
<div id="orders-by-status">
<%= link_to "Ordered", admin_dashboard_path(:status_hold => "Ordered")%> |
<%= link_to "Paid", admin_dashboard_path(:status_hold => "Paid")%> |
<%= link_to "Cancelled", admin_dashboard_path(:status_hold => "Cancelled")%> |
<%= link_to "Completed", admin_dashboard_path(:status_hold => "Completed")%> |
<%= link_to "All Orders", admin_dashboard_path(:status_hold => nil)%> |
<%= link_to "View All Items", admin_beans_path%>
</div>
<section class="admin-dash-order-items">
<h3><%= @order_list_title %>:</h3>
<div class ="order_list">
  <%@orders.each do |order| %>
    <ul class="orders">
      <h4><%=link_to "Order #{order.id}", admin_order_path(order)%></h4>
      <li> Contents: <br>
      <ol>
          <%order.order_beans.each do |order_bean|%>
         <li><strong><%=order_bean.item_title%></strong><br>
          Quantity: <%=order_bean.quantity%> <br>
          <% end %>
          </ol>
          </li>
      <li> Total Price: $<%=order.total_price%></li>
      <li> Status: <%=order.status%></li>
      Change Status:
      <%= link_to("Cancel", admin_order_path(order, :status => 'Cancelled'), method: :put) if order.status == "Paid"||order.status =="Ordered"%>
      <%= link_to("Paid", admin_order_path(order, :status => 'Paid'), method: :put) if order.status == "Ordered" %>
      <%= link_to("Completed", admin_order_path(order, :status => 'Completed'), method: :put) if order.status == "Paid"%>
    </ul><br>
  <% end %>
</div>
</section>
<aside>
<div class="order-status">
  <h3>Order Count by Status:</h3>
  <ul>
  <li id="ordered-count">Ordered Count: <%= @all_orders.ordered_count %></li><br>
  <li id="paid-count">Paid Count: <%= @all_orders.paid_count %></li><br>
  <li id="cancelled-count">Cancelled Count: <%= @all_orders.cancelled_count %></li><br>
  <li id="completed-count">Completed Count: <%= @all_orders.completed_count %></li>
  <ul>
</div>
</aside>

app/views/application/dashboard.html.erb
<h1 align = center>Abandoned Camel Coffee Mercantile</h1>

<div class="container">

  <div class="jumbotron">
    <div class="row">
      <div class ="col-md-6">
        <h2 align=center>About Us</h2>
        <p>
          Your trusted source for organic, fair-trade, non-GMO liquid happiness.
          We're happy to have you. Please enjoy yourself browsing around and
          buy some happiness.
        </p>
        <p align=center><a class="btn btn-success btn-lg" href="/beans" role="button">Shop Now</a></p>
      </div>
      <div class="col-md-6">
        <img src="http://www.stanscoffee.com/wp-content/uploads/2014/11/coffee_bag.jpg" alt="coffee bag">
      </div>
    </div>
</div>

app/views/application/index.html.erb
<h1>Abandoned Camel Coffee Mercantile</h1>