config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#dashboard"

  resources :beans, only: [ :index, :show ]

  resources :categories, only: [:index]

  resources :cart_items

  resources :cart

  resources :users, only: [:new, :create]

  resources :sessions, only: [:destroy]

  namespace :admin do
    get 'dashboard', to: 'dashboard#dashboard'
    resources :orders, only: [:update, :show]
    resources :beans, only: [:new, :create, :index, :edit, :show, :update]
  end

  resources :orders, only: [:create, :show, :index]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/dashboard', to: 'users#show'

  get '/:category_name', to: 'categories#show', as: 'category'


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AbandonedCamelCoffeeMercantile</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Abandoned Camel Coffee Mercantile</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="categories">Categories <span class="sr-only">(current)</span></a></li>
        <li><a href="/beans">All Beans</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if session[:user_id] == nil %>
          <li><a href="/login" class='login'>Login</a></li>
        <% else %>
          <li class='logout'><%= link_to "Logout", '/logout', method: :delete %></li>
          <% if current_user.role == "admin" %>
          <li class='dashboard'><%= link_to "Admin Dashboard", admin_dashboard_path, method: :get %></li>
          <% else %>
          <li class='dashboard'><%= link_to "Dashboard", dashboard_path, method: :get %></li>
          <% end %>
        <% end %>
        <li><a href="/cart">Cart ( <%= @cart.cart_count %> )</a></li>
      </ul>
    </div>
  </div>
</nav>

<div style='text-align:center'>
<% flash.each do |type, message| %>
    <% if type == "success" %>
    <%= content_tag :div, sanitize(message), class:"alert-success" %>
    <% elsif type == "danger" %>
    <%= content_tag :div, sanitize(message), class:"alert-danger" %>
    <% else %>
    <%= content_tag :div, sanitize(message), class:"type" %>
    <% end %>
  <% end %>
</div>
    <%= yield %>


  </body>
  <footer class="footer">
    <div class="container">
      <span class="text-muted">Abandoned Camel Coffee Mercantile</span>
      <span class="text-muted"><a href="/beans">All Beans</a></span>
    </div>
  </footer>

</html>